import { db } from "@bizbrain/db";
import { regenerateContentDraft, runPipelineJob, updateContentDraftAssetStatus, updateContentDraftMediaCandidateStatus, updateContentDraftStatStatus, updateContentDraftStatus } from "../actions";
import { formatDate, formatListInput, formatSourceAttribution, getDashboardData, readSearchParam } from "../dashboard-data";
import { EmptyState } from "../dashboard-ui";

export const dynamic = "force-dynamic";

type PageProps = {
  searchParams?: Promise<Record<string, string | string[] | undefined>>;
};

export default async function SocialDraftsPage({ searchParams }: PageProps) {
  const resolvedSearchParams = (await searchParams) ?? {};
  const dashboard = await getDashboardData();
  const drafts = (await getSocialDrafts()) as any[];
  const query = readSearchParam(resolvedSearchParams, "q");
  const channel = readSearchParam(resolvedSearchParams, "channel");
  const topicId = readSearchParam(resolvedSearchParams, "topicId");
  const status = readSearchParam(resolvedSearchParams, "status");
  const assetStatus = readSearchParam(resolvedSearchParams, "assetStatus");
  const reviewMode = readSearchParam(resolvedSearchParams, "reviewMode");

  const filteredDrafts = drafts.filter((draft) => {
    const matchesQuery =
      !query ||
      [
        draft.title,
        draft.topic?.name ?? "",
        draft.hook ?? "",
        draft.thesis ?? "",
        draft.copyFramework?.name ?? "",
        draft.styleProfile?.name ?? "",
        draft.sourceBrief?.title ?? "",
        draft.sourceBrief?.themeSummary ?? "",
        draft.sourceBrief?.operatorTakeaway ?? "",
        draft.sourceIdea?.title ?? "",
        draft.sourceIdea?.problemSummary ?? "",
        draft.sourceIdea?.solutionConcept ?? "",
        draft.sourceIdea?.targetCustomer ?? "",
        draft.sourceIdea?.cluster?.title ?? ""
      ]
        .join(" ")
        .toLowerCase()
        .includes(query.trim().toLowerCase());
    const matchesChannel = !channel || draft.targetChannel === channel;
    const matchesTopic = !topicId || draft.topicId === topicId;
    const matchesStatus = !status || draft.status === status;
    const matchesAssetStatus = !assetStatus || (draft.assetStatus ?? "draft") === assetStatus;
    const supportingStats = readSupportingStats(draft.supportingStatsJson);
    const mediaCandidates = readMediaCandidates(draft.assetCandidatesJson);
    const matchesReviewMode =
      !reviewMode ||
      (reviewMode === "ready-only"
        ? draftHasReadyEvidence({ supportingStats, mediaCandidates })
        : reviewMode === "needs-review"
          ? draftNeedsReview({ supportingStats, mediaCandidates, assetStatus: draft.assetStatus ?? "draft" })
          : true);

    return matchesQuery && matchesChannel && matchesTopic && matchesStatus && matchesAssetStatus && matchesReviewMode;
  });

  const socialTopics = dashboard.topics.filter((topic) => topic.researchStream.slug === "social-media-research");

  return (
    <main className="contentPage">
      <section className="hero heroCompact">
        <p className="eyebrow">BizBrain</p>
        <h1>Social Drafts</h1>
        <p className="lede">
          Review, filter, and triage generated LinkedIn/X drafts here. Use statuses like `promising`, `revisit`, and `ignore`
          to create a lightweight editorial workflow before building the fuller approval system.
        </p>
      </section>

      <section className="dashboardGrid dashboardGridTwoCol">
        <article className="card controlCard">
          <div className="cardHeader">
            <h2>Generate social drafts</h2>
            <span className="badge">Social</span>
          </div>
          <form action={runPipelineJob}>
            <input name="jobName" type="hidden" value="daily-enrich-score" />
            <button className="jobButton" type="submit">
              Run daily-enrich-score
            </button>
          </form>
          <p className="helperText">
            Social drafts are generated by the shared enrich pipeline. Run `daily-enrich-score` when you want fresh draft output.
          </p>
        </article>

        <article className="card cardTall">
          <div className="cardHeader">
            <h2>All social drafts</h2>
            <span className="badge">Review</span>
          </div>
          <form className="filterForm filterFormDrafts" method="get">
            <label className="fieldLabel">
              Search drafts
              <input className="fieldInput" defaultValue={query} name="q" placeholder="Search title, hook, idea, framework, style" type="text" />
            </label>
            <label className="fieldLabel">
              Channel
              <select className="fieldInput" defaultValue={channel} name="channel">
                <option value="">All channels</option>
                <option value="linkedin">LinkedIn</option>
                <option value="x">X</option>
              </select>
            </label>
            <label className="fieldLabel">
              Topic
              <select className="fieldInput" defaultValue={topicId} name="topicId">
                <option value="">All topics</option>
                {socialTopics.map((topic) => (
                  <option key={topic.id} value={topic.id}>
                    {topic.name}
                  </option>
                ))}
              </select>
            </label>
            <label className="fieldLabel">
              Status
              <select className="fieldInput" defaultValue={status} name="status">
                <option value="">All statuses</option>
                <option value="draft">draft</option>
                <option value="promising">promising</option>
                <option value="revisit">revisit</option>
                <option value="ignore">ignore</option>
                <option value="publish-later">publish-later</option>
              </select>
            </label>
            <label className="fieldLabel">
              Asset review
              <select className="fieldInput" defaultValue={assetStatus} name="assetStatus">
                <option value="">All asset states</option>
                <option value="draft">draft</option>
                <option value="review-required">review-required</option>
                <option value="approved">approved</option>
                <option value="reference-only">reference-only</option>
                <option value="rejected">rejected</option>
              </select>
            </label>
            <label className="fieldLabel">
              Review mode
              <select className="fieldInput" defaultValue={reviewMode} name="reviewMode">
                <option value="">All drafts</option>
                <option value="ready-only">Ready only</option>
                <option value="needs-review">Needs review</option>
              </select>
            </label>
            <button className="jobButton jobButtonSecondary" type="submit">
              Filter drafts
            </button>
          </form>
          <p className="helperText">
            Showing {filteredDrafts.length} of {drafts.length} social draft(s).
          </p>
          {drafts.length === 0 ? (
            <EmptyState message="No social drafts exist yet. Run `daily-enrich-score` to generate them." />
          ) : filteredDrafts.length === 0 ? (
            <EmptyState message="No social drafts matched the current filters." />
          ) : (
            <div className="stack">
              {filteredDrafts.map((draft) => {
                const fitPreview = buildDraftTopicFitPreview(draft);
                const supportingStats = readSupportingStats(draft.supportingStatsJson);
                const signalEvidenceStats = readSupportingStats((draft as { signalEvidenceStatsJson?: unknown }).signalEvidenceStatsJson);
                const mediaCandidates = readMediaCandidates(draft.assetCandidatesJson);

                return (
                  <details className="adminDisclosure" key={draft.id}>
                    <summary className="adminDisclosureSummary">
                      <div>
                        <p className="rowTitle">{draft.title}</p>
                        <p className="rowMeta">
                          {draft.targetChannel} · {draft.topic?.name ?? "No topic"} · {draft.copyFramework?.name ?? "No framework"} ·{" "}
                          {draft.styleProfile?.name ?? "No style"} · quality {draft.qualityScore?.toFixed(1) ?? "n/a"} · {draft.status}
                        </p>
                        <p className="rowMeta">Updated {formatDate(draft.updatedAt)}</p>
                      </div>
                      <span className={`status status-${normalizeDraftStatus(draft.status)}`}>{draft.status}</span>
                    </summary>
                    <div className="draftDetailGrid">
                      <div className="draftPrimary">
                        <p className="rowBody"><strong>Hook:</strong> {draft.hook ?? "No hook yet."}</p>
                        <p className="rowBody"><strong>Thesis:</strong> {draft.thesis ?? "No thesis yet."}</p>
                        <p className="rowBody"><strong>Audience:</strong> {draft.targetAudience ?? "No target audience yet."}</p>
                        <p className="rowBody"><strong>Supporting points:</strong> {formatListInput(draft.supportingPointsJson) || "No supporting points yet."}</p>
                        <p className="rowBody"><strong>CTA:</strong> {draft.cta ?? "No CTA yet."}</p>
                        <p className="rowBody"><strong>Source brief:</strong> {draft.sourceBrief?.title ?? draft.sourceIdea?.title ?? "No linked research brief."}</p>
                        <div className="evidenceSection">
                          <p className="rowBody">
                            <strong>Source research context:</strong>
                          </p>
                          {draft.sourceBrief ? (
                            <div className="evidenceCard">
                              <p className="rowMeta">
                                {draft.sourceBrief.cluster?.title ?? "Cluster pending"}
                                {draft.sourceBrief.topic?.name ? ` · ${draft.sourceBrief.topic.name}` : ""}
                              </p>
                              <p className="rowBody">
                                <strong>Theme:</strong> {draft.sourceBrief.themeSummary ?? "No theme summary yet."}
                              </p>
                              <p className="rowBody">
                                <strong>Audience insight:</strong> {draft.sourceBrief.audienceInsight ?? "No audience insight yet."}
                              </p>
                              <p className="rowBody">
                                <strong>Operator takeaway:</strong> {draft.sourceBrief.operatorTakeaway ?? "No operator takeaway yet."}
                              </p>
                              <p className="rowBody">
                                <strong>Evidence:</strong> {draft.sourceBrief.evidenceSummary ?? "No evidence summary yet."}
                              </p>
                              <p className="rowMeta">
                                {formatSourceAttribution(draft.sourceBrief.sourceAttributionJson)}
                              </p>
                            </div>
                          ) : draft.sourceIdea ? (
                            <div className="evidenceCard">
                              <p className="rowMeta">
                                {draft.sourceIdea.businessType ?? "Business type pending"}
                                {draft.sourceIdea.targetCustomer ? ` · ${draft.sourceIdea.targetCustomer}` : ""}
                                {draft.sourceIdea.cluster?.title ? ` · ${draft.sourceIdea.cluster.title}` : ""}
                              </p>
                              <p className="rowBody">
                                <strong>Problem:</strong> {draft.sourceIdea.problemSummary ?? "No problem summary yet."}
                              </p>
                              <p className="rowBody">
                                <strong>Solution:</strong> {draft.sourceIdea.solutionConcept ?? "No solution concept yet."}
                              </p>
                              <p className="rowBody">
                                <strong>Evidence:</strong> {draft.sourceIdea.evidenceSummary ?? "No evidence summary yet."}
                              </p>
                              <p className="rowMeta">
                                {formatSourceAttribution(draft.sourceIdea.sourceAttributionJson)}
                              </p>
                            </div>
                          ) : (
                            <p className="rowMeta">No linked idea context yet.</p>
                          )}
                        </div>
                        <pre className="draftPreview">{draft.draftMarkdown ?? "No draft body yet."}</pre>
                      </div>
                      <div className="draftSidebar">
                        <div className="stackCompact">
                        <p className="rowMeta"><strong>Visual brief:</strong> {readObjectField(draft.visualBriefJson, "concept") ?? "No visual brief yet."}</p>
                        <p className="rowMeta"><strong>Infographic creative direction:</strong> {readObjectField(draft.infographicCreativeBriefJson, "creativeDirection") ?? "No creative brief yet."}</p>
                        <p className="rowMeta">
                          <strong>External insight stats:</strong> {supportingStats.length}
                          {supportingStats.length > 0 ? ` · ${summarizeStatSourceClasses(supportingStats)}` : ""}
                        </p>
                        <p className="rowMeta">
                          <strong>Signal evidence:</strong> {signalEvidenceStats.length}
                          {signalEvidenceStats.length > 0 ? ` · ${summarizeStatSourceClasses(signalEvidenceStats)}` : ""}
                        </p>
                        <p className="rowMeta"><strong>Infographic format:</strong> {draft.infographicFormat ?? "Not set"}</p>
                        <p className="rowMeta"><strong>Infographic panels:</strong> {formatListInput(draft.infographicPanelsJson) || "No panel outline yet."}</p>
                        <p className="rowMeta"><strong>Asset mode:</strong> {draft.assetMode ?? "none"}</p>
                        <p className="rowMeta"><strong>Asset review:</strong> {draft.assetStatus ?? "draft"}</p>
                        </div>
                        <div className="evidenceSection">
                          <p className="rowBody">
                            <strong>Infographic creative brief:</strong>
                          </p>
                          {!draft.infographicCreativeBriefJson || typeof draft.infographicCreativeBriefJson !== "object" ? (
                            <p className="rowMeta">No creative-production brief is attached yet.</p>
                          ) : (
                            <div className="evidenceCard">
                              <p className="rowBody"><strong>Objective:</strong> {readObjectField(draft.infographicCreativeBriefJson, "objective") ?? "No objective recorded."}</p>
                              <p className="rowBody"><strong>Visual style:</strong> {readObjectField(draft.infographicCreativeBriefJson, "visualStyle") ?? "No visual style recorded."}</p>
                              <p className="rowBody"><strong>Layout strategy:</strong> {readObjectField(draft.infographicCreativeBriefJson, "layoutStrategy") ?? "No layout strategy recorded."}</p>
                              <p className="rowBody"><strong>Chart/diagram:</strong> {readObjectField(draft.infographicCreativeBriefJson, "chartOrDiagramType") ?? "No chart direction recorded."}</p>
                              <p className="rowBody"><strong>Image source strategy:</strong> {readObjectField(draft.infographicCreativeBriefJson, "imageSourceStrategy") ?? "No source strategy recorded."}</p>
                              <p className="rowBody"><strong>Composition prompt:</strong> {readObjectField(draft.infographicCreativeBriefJson, "compositionPrompt") ?? "No composition prompt recorded."}</p>
                              <p className="rowBody"><strong>Text hierarchy:</strong> {formatListInput(readObjectArrayField(draft.infographicCreativeBriefJson, "textHierarchy")) || "No hierarchy recorded."}</p>
                              <p className="rowBody"><strong>Panel prompts:</strong> {formatListInput(readObjectArrayField(draft.infographicCreativeBriefJson, "panelPrompts")) || "No panel prompts recorded."}</p>
                              <p className="rowBody"><strong>Avoid notes:</strong> {formatListInput(readObjectArrayField(draft.infographicCreativeBriefJson, "avoidNotes")) || "No avoid notes recorded."}</p>
                              <pre className="draftPreview">{readObjectField(draft.infographicCreativeBriefJson, "aiImagePrompt") ?? "No AI image prompt recorded."}</pre>
                            </div>
                          )}
                        </div>
                        <div className="evidenceSection">
                          <p className="rowBody">
                            <strong>External insight statistics:</strong>
                          </p>
                          {supportingStats.length === 0 ? (
                            <p className="rowMeta">No publishable external insight statistics are attached yet.</p>
                          ) : (
                            <div className="stack">
                              {supportingStats.map((stat, index) => (
                                <div className="evidenceCard" key={`${draft.id}-stat-${index}`}>
                                  <p className="rowMeta">
                                    <span className="badge">{stat.sourceClassLabel}</span>
                                    {" "}
                                    <span className={`status status-${normalizeStatReviewStatus(stat.reviewStatus)}`}>{stat.reviewStatus}</span>
                                  </p>
                                  <p className="rowTitle">{stat.claim}</p>
                                  <p className="rowBody">
                                    <strong>Angle:</strong> {stat.plainLanguageAngle}
                                  </p>
                                  <p className="rowBody">
                                    <strong>Usage:</strong> {stat.recommendedUsage}
                                  </p>
                                  <p className="rowMeta">
                                    {stat.sourceName} · {stat.sourceDate ?? "date not stored"}
                                  </p>
                                  <p className="rowBody">
                                    <strong>Freshness:</strong> {stat.freshnessNote}
                                  </p>
                                  <p className="rowBody">
                                    <strong>Confidence:</strong> {stat.confidenceNote}
                                  </p>
                                  <p className="rowMeta">
                                    <strong>Source:</strong>{" "}
                                    {stat.sourceUrl ? (
                                      <a href={stat.sourceUrl} rel="noreferrer" target="_blank">
                                        {stat.sourceUrl}
                                      </a>
                                    ) : (
                                      "No source URL stored"
                                    )}
                                  </p>
                                  <div className="jobButtons">
                                    {[
                                      ["approved", "Approve"],
                                      ["use-with-caution", "Use With Caution"],
                                      ["rejected", "Reject"],
                                      ["pending", "Reset"]
                                    ].map(([reviewStatus, label]) => (
                                      <form action={updateContentDraftStatStatus} key={`${draft.id}-stat-${index}-${reviewStatus}`}>
                                        <input name="id" type="hidden" value={draft.id} />
                                        <input name="statIndex" type="hidden" value={String(index)} />
                                        <input name="reviewStatus" type="hidden" value={reviewStatus} />
                                        <button className="jobButton jobButtonSecondary" type="submit">
                                          {label}
                                        </button>
                                      </form>
                                    ))}
                                  </div>
                                </div>
                              ))}
                            </div>
                          )}
                        </div>
                        <div className="evidenceSection">
                          <p className="rowBody">
                            <strong>Signal evidence:</strong>
                          </p>
                          {signalEvidenceStats.length === 0 ? (
                            <p className="rowMeta">No signal-evidence stats are attached yet.</p>
                          ) : (
                            <div className="stack">
                              {signalEvidenceStats.map((stat, index) => (
                                <div className="evidenceCard" key={`${draft.id}-signal-stat-${index}`}>
                                  <p className="rowMeta">
                                    <span className="badge">{stat.sourceClassLabel}</span>
                                  </p>
                                  <p className="rowTitle">{stat.claim}</p>
                                  <p className="rowBody">
                                    <strong>Angle:</strong> {stat.plainLanguageAngle}
                                  </p>
                                  <p className="rowBody">
                                    <strong>Usage:</strong> {stat.recommendedUsage}
                                  </p>
                                  <p className="rowMeta">
                                    {stat.sourceName} · {stat.sourceDate ?? "date not stored"}
                                  </p>
                                  <p className="rowBody">
                                    <strong>Freshness:</strong> {stat.freshnessNote}
                                  </p>
                                  <p className="rowBody">
                                    <strong>Confidence:</strong> {stat.confidenceNote}
                                  </p>
                                  <p className="rowMeta">
                                    <strong>Source:</strong>{" "}
                                    {stat.sourceUrl ? (
                                      <a href={stat.sourceUrl} rel="noreferrer" target="_blank">
                                        {stat.sourceUrl}
                                      </a>
                                    ) : (
                                      "No source URL stored"
                                    )}
                                  </p>
                                </div>
                              ))}
                            </div>
                          )}
                        </div>
                        <div className="evidenceSection">
                          <p className="rowBody">
                            <strong>Media policy:</strong>
                          </p>
                          <div className="evidenceCard">
                            <p className="rowMeta">
                              Preferred sources: {formatListInput(readObjectArrayField(draft.mediaPolicyJson, "preferredSourceClasses")) || "none"}
                            </p>
                            <p className="rowMeta">
                              Direct-use exclusions: {formatListInput(readObjectArrayField(draft.mediaPolicyJson, "prohibitedDirectUseSources")) || "none"}
                            </p>
                            <p className="rowBody">
                              {formatListInput(readObjectArrayField(draft.mediaPolicyJson, "publishingNotes")) || "No publishing notes yet."}
                            </p>
                          </div>
                        </div>
                        <div className="evidenceSection">
                          <p className="rowBody">
                            <strong>Media candidates:</strong>
                          </p>
                          {mediaCandidates.length === 0 ? (
                            <p className="rowMeta">No media candidates yet.</p>
                          ) : (
                            <div className="stack">
                              {mediaCandidates.map((candidate, index) => (
                                <div className="evidenceCard" key={`${draft.id}-candidate-${index}`}>
                                  <p className="rowTitle">{candidate.label}</p>
                                  <p className="rowMeta">
                                    {candidate.sourceType} · {candidate.usageStatus}
                                    {` · review ${candidate.reviewStatus}`}
                                    {candidate.originDomain ? ` · ${candidate.originDomain}` : ""}
                                  </p>
                                  <p className="rowBody">
                                    <strong>License:</strong> {candidate.licenseLabel ?? "Verify on origin site"}
                                  </p>
                                  <p className="rowBody">
                                    <strong>Attribution:</strong> {candidate.attributionText ?? "No attribution guidance stored."}
                                  </p>
                                  <p className="rowBody">
                                    <strong>Rights notes:</strong> {candidate.rightsNotes.join(" ") || "No rights notes."}
                                  </p>
                                  <p className="rowMeta">
                                    {candidate.originUrl ? (
                                      <>
                                        <strong>Origin:</strong> <a href={candidate.originUrl} rel="noreferrer" target="_blank">{candidate.originUrl}</a>
                                      </>
                                    ) : (
                                      "No origin URL stored."
                                    )}
                                  </p>
                                  <div className="jobButtons">
                                    {[
                                      ["approved", "Approve"],
                                      ["use-with-caution", "Use With Caution"],
                                      ["rejected", "Reject"],
                                      ["reference-only", "Reference Only"],
                                      ["pending", "Reset"]
                                    ].map(([reviewStatus, label]) => (
                                      <form action={updateContentDraftMediaCandidateStatus} key={`${draft.id}-candidate-${index}-${reviewStatus}`}>
                                        <input name="id" type="hidden" value={draft.id} />
                                        <input name="candidateIndex" type="hidden" value={String(index)} />
                                        <input name="reviewStatus" type="hidden" value={reviewStatus} />
                                        <button className="jobButton jobButtonSecondary" type="submit">
                                          {label}
                                        </button>
                                      </form>
                                    ))}
                                  </div>
                                </div>
                              ))}
                            </div>
                          )}
                        </div>
                        <div className="evidenceSection">
                          <p className="rowBody">
                            <strong>Topic fit:</strong>
                          </p>
                          <div className="stack">
                            <div className="evidenceCard">
                              <p className="rowTitle">{draft.topic?.name ?? "No topic linked"}</p>
                              <p className="rowMeta">
                                {draft.topic?.researchStream?.name ?? "No stream"} · content channels {formatListInput(draft.topic?.enabledChannelsJson) || "none"}
                              </p>
                              <p className="rowBody">{fitPreview.reason}</p>
                              <p className="rowMeta">Preview terms: {fitPreview.terms.join(", ") || "none"}</p>
                            </div>
                          </div>
                        </div>
                        <div className="jobButtons">
                          <form action={regenerateContentDraft}>
                            <input name="id" type="hidden" value={draft.id} />
                            <button className="jobButton" type="submit">
                              Regenerate
                            </button>
                          </form>
                          {[
                            ["promising", "Promising"],
                            ["revisit", "Revisit"],
                            ["ignore", "Ignore"],
                            ["publish-later", "Publish Later"],
                            ["draft", "Reset"]
                          ].map(([nextStatus, label]) => (
                            <form action={updateContentDraftStatus} key={nextStatus}>
                              <input name="id" type="hidden" value={draft.id} />
                              <input name="status" type="hidden" value={nextStatus} />
                              <button className="jobButton jobButtonSecondary" type="submit">
                                {label}
                              </button>
                            </form>
                          ))}
                          {[
                            ["review-required", "Needs Review"],
                            ["approved", "Approve Media"],
                            ["reference-only", "Reference Only"],
                            ["rejected", "Reject Media"],
                            ["draft", "Reset Media"]
                          ].map(([nextAssetStatus, label]) => (
                            <form action={updateContentDraftAssetStatus} key={nextAssetStatus}>
                              <input name="id" type="hidden" value={draft.id} />
                              <input name="assetStatus" type="hidden" value={nextAssetStatus} />
                              <button className="jobButton jobButtonSecondary" type="submit">
                                {label}
                              </button>
                            </form>
                          ))}
                        </div>
                      </div>
                    </div>
                  </details>
                );
              })}
            </div>
          )}
        </article>
      </section>
    </main>
  );
}

async function getSocialDrafts() {
  return (db as any).contentDraft.findMany({
    where: {
      researchStreamId: "stream-social-media-research"
    },
    orderBy: [{ updatedAt: "desc" }, { qualityScore: "desc" }],
    include: {
      topic: {
        include: {
          researchStream: true
        }
      },
      copyFramework: true,
      styleProfile: true,
      sourceBrief: {
        include: {
          topic: true,
          cluster: {
            select: {
              title: true
            }
          }
        }
      },
      sourceIdea: {
        include: {
          cluster: {
            select: {
              title: true
            }
          }
        }
      }
    }
  });
}

function readObjectField(value: unknown, key: string) {
  if (!value || typeof value !== "object" || !(key in value)) {
    return null;
  }

  const candidate = (value as Record<string, unknown>)[key];
  return typeof candidate === "string" ? candidate : null;
}

function readObjectArrayField(value: unknown, key: string) {
  if (!value || typeof value !== "object" || !(key in value)) {
    return [];
  }

  const candidate = (value as Record<string, unknown>)[key];
  return Array.isArray(candidate) ? candidate.filter((entry): entry is string => typeof entry === "string") : [];
}

function readMediaCandidates(value: unknown) {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .filter((entry): entry is Record<string, unknown> => Boolean(entry) && typeof entry === "object")
    .map((entry) => ({
      label: typeof entry.label === "string" ? entry.label : "Untitled candidate",
      sourceType: typeof entry.sourceType === "string" ? entry.sourceType : "unknown",
      originUrl: typeof entry.originUrl === "string" ? entry.originUrl : null,
      originDomain: typeof entry.originDomain === "string" ? entry.originDomain : null,
      licenseLabel: typeof entry.licenseLabel === "string" ? entry.licenseLabel : null,
      attributionText: typeof entry.attributionText === "string" ? entry.attributionText : null,
      usageStatus: typeof entry.usageStatus === "string" ? entry.usageStatus : "review-required",
      reviewStatus:
        typeof entry.reviewStatus === "string" && ["pending", "approved", "use-with-caution", "rejected", "reference-only"].includes(entry.reviewStatus)
          ? entry.reviewStatus
          : typeof entry.usageStatus === "string" && entry.usageStatus === "reference-only"
            ? "reference-only"
            : "pending",
      rightsNotes: Array.isArray(entry.rightsNotes)
        ? entry.rightsNotes.filter((note): note is string => typeof note === "string")
        : []
    }));
}

function readSupportingStats(value: unknown) {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .filter((entry): entry is Record<string, unknown> => Boolean(entry) && typeof entry === "object")
    .map((entry) => ({
      claim: typeof entry.claim === "string" ? entry.claim : "No claim recorded.",
      plainLanguageAngle: typeof entry.plainLanguageAngle === "string" ? entry.plainLanguageAngle : "No angle recorded.",
      sourceName: typeof entry.sourceName === "string" ? entry.sourceName : "Unknown source",
      sourceUrl: typeof entry.sourceUrl === "string" && entry.sourceUrl.trim().length > 0 ? entry.sourceUrl : null,
      sourceDate: typeof entry.sourceDate === "string" ? entry.sourceDate : null,
      freshnessNote: typeof entry.freshnessNote === "string" ? entry.freshnessNote : "No freshness note recorded.",
      confidenceNote: typeof entry.confidenceNote === "string" ? entry.confidenceNote : "No confidence note recorded.",
      recommendedUsage: typeof entry.recommendedUsage === "string" ? entry.recommendedUsage : "No usage guidance recorded.",
      reviewStatus:
        typeof entry.reviewStatus === "string" && ["pending", "approved", "use-with-caution", "rejected"].includes(entry.reviewStatus)
          ? entry.reviewStatus
          : "pending",
      sourceClassLabel: inferStatSourceClass(
        typeof entry.sourceName === "string" ? entry.sourceName : "Unknown source",
        typeof entry.sourceUrl === "string" ? entry.sourceUrl : null
      )
    }));
}

function inferStatSourceClass(sourceName: string, sourceUrl: string | null) {
  const normalizedName = sourceName.toLowerCase();
  const normalizedUrl = (sourceUrl ?? "").toLowerCase();

  if (normalizedName.includes("google trends") || normalizedUrl.includes("trends.google.com")) {
    return "Google Trends";
  }

  if (normalizedName.includes("product hunt") || normalizedUrl.includes("producthunt.com")) {
    return "Product Hunt";
  }

  if (normalizedName.includes("bizbrain") || normalizedUrl.includes("app.bizbrain.local")) {
    return "Cluster Evidence";
  }

  return "External Evidence";
}

function summarizeStatSourceClasses(
  stats: Array<ReturnType<typeof readSupportingStats>[number]>
) {
  const labels = [...new Set(stats.map((stat) => stat.sourceClassLabel))];
  return labels.join(", ");
}

function normalizeStatReviewStatus(status: string) {
  if (status === "approved") {
    return "enabled";
  }

  if (status === "use-with-caution") {
    return "running";
  }

  if (status === "rejected") {
    return "failed";
  }

  return "skipped";
}

function draftHasReadyEvidence(input: {
  supportingStats: ReturnType<typeof readSupportingStats>;
  mediaCandidates: ReturnType<typeof readMediaCandidates>;
}) {
  const hasApprovedStat = input.supportingStats.some((stat) => stat.reviewStatus === "approved");
  const hasApprovedMedia = input.mediaCandidates.some((candidate) => candidate.reviewStatus === "approved");

  return hasApprovedStat || hasApprovedMedia;
}

function draftNeedsReview(input: {
  supportingStats: ReturnType<typeof readSupportingStats>;
  mediaCandidates: ReturnType<typeof readMediaCandidates>;
  assetStatus: string;
}) {
  const hasPendingStat = input.supportingStats.some((stat) => stat.reviewStatus === "pending");
  const hasPendingMedia = input.mediaCandidates.some((candidate) => candidate.reviewStatus === "pending");

  return hasPendingStat || hasPendingMedia || input.assetStatus === "review-required";
}

function normalizeDraftStatus(status: string) {
  if (status === "ignore") {
    return "failed";
  }

  if (status === "promising" || status === "publish-later") {
    return "enabled";
  }

  if (status === "revisit") {
    return "running";
  }

  return "skipped";
}

function buildDraftTopicFitPreview(draft: Awaited<ReturnType<typeof getSocialDrafts>>[number]) {
  const topic = draft.topic;
  const topicChannels = formatListInput(topic?.enabledChannelsJson) || "none";
  const terms = collectDraftTerms(draft);
  const overlap = topic ? countDraftTopicOverlap(terms, topic) : 0;
  const reasons = [
    draft.targetChannel ? `draft channel ${draft.targetChannel}` : null,
    topic && Array.isArray(topic.enabledChannelsJson) && topic.enabledChannelsJson.includes(draft.targetChannel)
      ? "channel enabled on topic"
      : null,
    overlap > 0 ? `${overlap} topic keyword match${overlap > 1 ? "es" : ""}` : null,
    draft.sourceIdea?.primaryTopicId && topic && draft.sourceIdea.primaryTopicId === topic.id ? "source idea already linked to topic" : null,
    draft.sourceBrief && topic && draft.sourceBrief.topicId === topic.id ? "brief already linked to topic" : null
  ].filter((reason): reason is string => Boolean(reason));

  return {
    terms,
    reason:
      reasons.join(" + ") ||
      `This draft is attached to the topic and targets ${draft.targetChannel} within channels ${topicChannels}.`
  };
}

function collectDraftTerms(draft: Awaited<ReturnType<typeof getSocialDrafts>>[number]) {
  const terms = [
    draft.title,
    draft.targetChannel,
    draft.hook ?? "",
    draft.thesis ?? "",
    draft.targetAudience ?? "",
    formatListInput(draft.supportingPointsJson),
    draft.cta ?? "",
    draft.topic?.name ?? "",
    draft.topic?.slug ?? "",
    draft.topic?.description ?? "",
    formatListInput(draft.topic?.keywordsJson),
    draft.sourceIdea?.title ?? "",
    draft.sourceIdea?.businessType ?? "",
    draft.sourceIdea?.targetCustomer ?? "",
    draft.sourceIdea?.problemSummary ?? "",
    draft.sourceIdea?.solutionConcept ?? "",
    draft.sourceIdea?.evidenceSummary ?? "",
    draft.sourceIdea?.cluster?.title ?? ""
  ]
    .join(" ")
    .toLowerCase()
    .split(/[^a-z0-9+-]+/i)
    .map((entry) => entry.trim())
    .filter((entry) => entry.length >= 3);

  return [...new Set(terms)];
}

function countDraftTopicOverlap(
  draftTerms: string[],
  topic: NonNullable<Awaited<ReturnType<typeof getSocialDrafts>>[number]["topic"]>
) {
  if (draftTerms.length === 0) {
    return 0;
  }

  const topicCorpus = [
    topic.name,
    topic.slug,
    topic.description ?? "",
    formatListInput(topic.keywordsJson),
    formatListInput(topic.sourcePreferencesJson)
  ]
    .join(" ")
    .toLowerCase();

  return draftTerms.filter((term) => topicCorpus.includes(term)).length;
}
