import { db } from "@bizbrain/db";
import { regenerateContentDraft, runPipelineJob, updateContentDraftStatus } from "../actions";
import { formatDate, formatListInput, getDashboardData, readSearchParam } from "../dashboard-data";
import { EmptyState } from "../dashboard-ui";

export const dynamic = "force-dynamic";

type PageProps = {
  searchParams?: Promise<Record<string, string | string[] | undefined>>;
};

export default async function SocialDraftsPage({ searchParams }: PageProps) {
  const resolvedSearchParams = (await searchParams) ?? {};
  const dashboard = await getDashboardData();
  const drafts = await getSocialDrafts();
  const query = readSearchParam(resolvedSearchParams, "q");
  const channel = readSearchParam(resolvedSearchParams, "channel");
  const topicId = readSearchParam(resolvedSearchParams, "topicId");
  const status = readSearchParam(resolvedSearchParams, "status");

  const filteredDrafts = drafts.filter((draft) => {
    const matchesQuery =
      !query ||
      [
        draft.title,
        draft.topic?.name ?? "",
        draft.hook ?? "",
        draft.thesis ?? "",
        draft.copyFramework?.name ?? "",
        draft.styleProfile?.name ?? "",
        draft.sourceIdea?.title ?? ""
      ]
        .join(" ")
        .toLowerCase()
        .includes(query.trim().toLowerCase());
    const matchesChannel = !channel || draft.targetChannel === channel;
    const matchesTopic = !topicId || draft.topicId === topicId;
    const matchesStatus = !status || draft.status === status;

    return matchesQuery && matchesChannel && matchesTopic && matchesStatus;
  });

  const socialTopics = dashboard.topics.filter((topic) => topic.researchStream.slug === "social-media-research");

  return (
    <main className="contentPage">
      <section className="hero heroCompact">
        <p className="eyebrow">BizBrain</p>
        <h1>Social Drafts</h1>
        <p className="lede">
          Review, filter, and triage generated LinkedIn/X drafts here. Use statuses like `promising`, `revisit`, and `ignore`
          to create a lightweight editorial workflow before building the fuller approval system.
        </p>
      </section>

      <section className="dashboardGrid dashboardGridTwoCol">
        <article className="card controlCard">
          <div className="cardHeader">
            <h2>Generate social drafts</h2>
            <span className="badge">Social</span>
          </div>
          <form action={runPipelineJob}>
            <input name="jobName" type="hidden" value="daily-enrich-score" />
            <button className="jobButton" type="submit">
              Run daily-enrich-score
            </button>
          </form>
          <p className="helperText">
            Social drafts are generated by the shared enrich pipeline. Run `daily-enrich-score` when you want fresh draft output.
          </p>
        </article>

        <article className="card cardTall">
          <div className="cardHeader">
            <h2>All social drafts</h2>
            <span className="badge">Review</span>
          </div>
          <form className="filterForm filterFormDrafts" method="get">
            <label className="fieldLabel">
              Search drafts
              <input className="fieldInput" defaultValue={query} name="q" placeholder="Search title, hook, idea, framework, style" type="text" />
            </label>
            <label className="fieldLabel">
              Channel
              <select className="fieldInput" defaultValue={channel} name="channel">
                <option value="">All channels</option>
                <option value="linkedin">LinkedIn</option>
                <option value="x">X</option>
              </select>
            </label>
            <label className="fieldLabel">
              Topic
              <select className="fieldInput" defaultValue={topicId} name="topicId">
                <option value="">All topics</option>
                {socialTopics.map((topic) => (
                  <option key={topic.id} value={topic.id}>
                    {topic.name}
                  </option>
                ))}
              </select>
            </label>
            <label className="fieldLabel">
              Status
              <select className="fieldInput" defaultValue={status} name="status">
                <option value="">All statuses</option>
                <option value="draft">draft</option>
                <option value="promising">promising</option>
                <option value="revisit">revisit</option>
                <option value="ignore">ignore</option>
                <option value="publish-later">publish-later</option>
              </select>
            </label>
            <button className="jobButton jobButtonSecondary" type="submit">
              Filter drafts
            </button>
          </form>
          <p className="helperText">
            Showing {filteredDrafts.length} of {drafts.length} social draft(s).
          </p>
          {drafts.length === 0 ? (
            <EmptyState message="No social drafts exist yet. Run `daily-enrich-score` to generate them." />
          ) : filteredDrafts.length === 0 ? (
            <EmptyState message="No social drafts matched the current filters." />
          ) : (
            <div className="stack">
              {filteredDrafts.map((draft) => (
                <details className="adminDisclosure" key={draft.id}>
                  <summary className="adminDisclosureSummary">
                    <div>
                      <p className="rowTitle">{draft.title}</p>
                      <p className="rowMeta">
                        {draft.targetChannel} · {draft.topic?.name ?? "No topic"} · {draft.copyFramework?.name ?? "No framework"} ·{" "}
                        {draft.styleProfile?.name ?? "No style"} · quality {draft.qualityScore?.toFixed(1) ?? "n/a"} · {draft.status}
                      </p>
                      <p className="rowMeta">Updated {formatDate(draft.updatedAt)}</p>
                    </div>
                    <span className={`status status-${normalizeDraftStatus(draft.status)}`}>{draft.status}</span>
                  </summary>
                  <div className="draftDetailGrid">
                    <div className="draftPrimary">
                      <p className="rowBody"><strong>Hook:</strong> {draft.hook ?? "No hook yet."}</p>
                      <p className="rowBody"><strong>Thesis:</strong> {draft.thesis ?? "No thesis yet."}</p>
                      <p className="rowBody"><strong>Audience:</strong> {draft.targetAudience ?? "No target audience yet."}</p>
                      <p className="rowBody"><strong>Supporting points:</strong> {formatListInput(draft.supportingPointsJson) || "No supporting points yet."}</p>
                      <p className="rowBody"><strong>CTA:</strong> {draft.cta ?? "No CTA yet."}</p>
                      <p className="rowBody"><strong>Source idea:</strong> {draft.sourceIdea?.title ?? "No linked idea."}</p>
                      <pre className="draftPreview">{draft.draftMarkdown ?? "No draft body yet."}</pre>
                    </div>
                    <div className="draftSidebar">
                      <div className="stackCompact">
                        <p className="rowMeta"><strong>Visual brief:</strong> {readObjectField(draft.visualBriefJson, "concept") ?? "No visual brief yet."}</p>
                        <p className="rowMeta"><strong>Infographic format:</strong> {draft.infographicFormat ?? "Not set"}</p>
                        <p className="rowMeta"><strong>Infographic panels:</strong> {formatListInput(draft.infographicPanelsJson) || "No panel outline yet."}</p>
                        <p className="rowMeta"><strong>Asset mode:</strong> {draft.assetMode ?? "none"}</p>
                      </div>
                      <div className="jobButtons">
                        <form action={regenerateContentDraft}>
                          <input name="id" type="hidden" value={draft.id} />
                          <button className="jobButton" type="submit">
                            Regenerate
                          </button>
                        </form>
                        {[
                          ["promising", "Promising"],
                          ["revisit", "Revisit"],
                          ["ignore", "Ignore"],
                          ["publish-later", "Publish Later"],
                          ["draft", "Reset"]
                        ].map(([nextStatus, label]) => (
                          <form action={updateContentDraftStatus} key={nextStatus}>
                            <input name="id" type="hidden" value={draft.id} />
                            <input name="status" type="hidden" value={nextStatus} />
                            <button className="jobButton jobButtonSecondary" type="submit">
                              {label}
                            </button>
                          </form>
                        ))}
                      </div>
                    </div>
                  </div>
                </details>
              ))}
            </div>
          )}
        </article>
      </section>
    </main>
  );
}

async function getSocialDrafts() {
  return db.contentDraft.findMany({
    where: {
      researchStreamId: "stream-social-media-research"
    },
    orderBy: [{ updatedAt: "desc" }, { qualityScore: "desc" }],
    include: {
      topic: true,
      copyFramework: true,
      styleProfile: true,
      sourceIdea: true
    }
  });
}

function readObjectField(value: unknown, key: string) {
  if (!value || typeof value !== "object" || !(key in value)) {
    return null;
  }

  const candidate = (value as Record<string, unknown>)[key];
  return typeof candidate === "string" ? candidate : null;
}

function normalizeDraftStatus(status: string) {
  if (status === "ignore") {
    return "failed";
  }

  if (status === "promising" || status === "publish-later") {
    return "enabled";
  }

  if (status === "revisit") {
    return "running";
  }

  return "skipped";
}
